Repository Irisvella/InventoryPilot, pull requests merged in 2025-04, with the labels that each got.

#375 CTPO Django Tests
  WarehousePilot_app/backend/auth_app/tests.py
  WarehousePilot_app/backend/orders/tests.py
  WarehousePilot_app/backend/orders/views.py
Labels: testing

#385 dark mode bugs fixed + enhancements
  WarehousePilot_app/frontend/src/components/Inventory_Picking_Logs/InventoryPickingLogs.jsx
  WarehousePilot_app/frontend/src/components/admin_manage_users/manage_users_table/App.tsx
  WarehousePilot_app/frontend/src/components/dashboard/CycleTime.jsx
  WarehousePilot_app/frontend/src/components/dashboard/KpiDashboard.jsx
  WarehousePilot_app/frontend/src/components/dashboard/dashboard.css
  WarehousePilot_app/frontend/src/components/inventory-stock/App.tsx
  WarehousePilot_app/frontend/src/components/kpis/CTPO/CTPOBarChart.jsx
  WarehousePilot_app/frontend/src/components/kpis/CTPO/CTPOPreview.jsx
  WarehousePilot_app/frontend/src/components/kpis/CTPO/CTPO_main.jsx
  WarehousePilot_app/frontend/src/components/manufacturing/StaffManufacturingTasks.jsx
  WarehousePilot_app/frontend/src/components/navbar/App.tsx
  WarehousePilot_app/frontend/src/components/orders/AssignedPickList.jsx
  WarehousePilot_app/frontend/src/components/orders/InventoyPickList.jsx
  WarehousePilot_app/frontend/src/components/orders/QAtasks.jsx
  WarehousePilot_app/frontend/src/index.css
Labels: bug, user story task, frontend

#410 Improving Orders Tests
  WarehousePilot_app/backend/orders/tests.py
  WarehousePilot_app/backend/orders/views.py
Labels: refactoring, testing
